<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **Launch Sites Locations Analysis with Folium**

Estimated time needed: **40** minutes

The launch success rate may depend on many factors such as payload mass, orbit type, and so on. It may also depend on the location and proximities of a launch site, i.e., the initial position of rocket trajectories. Finding an optimal location for building a launch site certainly involves many factors and hopefully we could discover some of the factors by analyzing the existing launch site locations.

In the previous exploratory data analysis labs, you have visualized the SpaceX launch dataset using `matplotlib` and `seaborn` and discovered some preliminary correlations between the launch site and success rates. In this lab, you will be performing more interactive visual analytics using `Folium`.

## Objectives

This lab contains the following tasks:
- **TASK 1:** Mark all launch sites on a map
- **TASK 2:** Mark the success/failed launches for each site on the map
- **TASK 3:** Calculate the distances between a launch site to its proximities

After completed the above tasks, you should be able to find some geographical patterns about launch sites.

Let's first import required Python packages for this lab:

In [1]:
!pip3 install folium
!pip3 install wget
!pip3 install pandas

Collecting folium
  Downloading folium-0.20.0-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting branca>=0.6.0 (from folium)
  Downloading branca-0.8.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: jinja2>=2.9 in /opt/conda/lib/python3.12/site-packages (from folium) (3.1.5)
Requirement already satisfied: numpy in /opt/conda/lib/python3.12/site-packages (from folium) (2.5.0)
Requirement already satisfied: requests in /opt/conda/lib/python3.12/site-packages (from folium) (2.32.3)
Collecting xyzservices (from folium)
  Downloading xyzservices-2026.3.0-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.12/site-packages (from jinja2>=2.9->folium) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests->folium) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests->folium) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.12/site-packages (from requests->folium) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.12/site-packages (from requests->folium) (2024.12.14)
Downloading folium-0.20.0-py2.py3-none-any.whl (113 kB)
Downloading branca-0.8.2-py3-none-any.whl (26 kB)
Downloading xyzservices-2026.3.0-py3-none-any.whl (94 kB)
Installing collected packages: xyzservices, branca, folium
Successfully installed branca-0.8.2 folium-0.20.0 xyzservices-2026.3.0
Collecting wget
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: wget
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9685 sha256=da9cc3d5625d74d8439d8a5a53793216d212161ec0d7d9137e10480a233bd165
  Stored in directory: /home/jupyterlab/.cache/pip/wheels/01/46/3b/e29ffbe4ebe614ff224bad40fc6a5773a67a163251585a13a9
Successfully built wget
Installing collected packages: wget
Successfully installed wget-3.2
Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import folium
import wget
import pandas as pd

In [3]:
# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

If you need to refresh your memory about folium, you may download and refer to this previous folium lab:

[Generating Maps with Python](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/DV0101EN-3-5-1-Generating-Maps-in-Python-py-v2.0.ipynb)

## Task 1: Mark all launch sites on a map

First, let's try to add each site's location on a map using site's latitude and longitude coordinates

The following dataset with the name `spacex_launch_geo.csv` is an augmented dataset with latitude and longitude added for each site. 


Tâche 1 : Localiser tous les sites de lancement sur une carte

Commençons par ajouter les coordonnées de latitude et de longitude de chaque site sur une carte.

Le fichier spacex_launch_geo.csv contient les données supplémentaires de chaque site, complétées par ses coordonnées de latitude et de longitude.

In [4]:
# Download and read the `spacex_launch_geo.csv`
spacex_csv_file = wget.download('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv')
spacex_df=pd.read_csv(spacex_csv_file)

Now, you can take a look at what are the coordinates for each site.

Vous pouvez maintenant consulter les coordonnées de chaque site.

In [5]:
# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

Above coordinates are just plain numbers that can not give you any intuitive insights about where are those launch sites. If you are very good at geography, you can interpret those numbers directly in your mind. If not, that's fine too. Let's visualize those locations by pinning them on a map.

We first need to create a folium `Map` object, with an initial center location to be NASA Johnson Space Center at Houston, Texas.


Les coordonnées ci-dessus ne sont que des nombres qui ne vous donnent aucune indication intuitive sur l'emplacement de ces sites de lancement. Si vous avez de solides connaissances en géographie, vous pouvez les interpréter mentalement. Sinon, ce n'est pas grave. Visualisons ces emplacements en les plaçant sur une carte.

Nous devons d'abord créer un objet Carte Folium, dont le centre initial sera le Centre spatial Johnson de la NASA à Houston, au Texas.

In [6]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

We could use `folium.Circle` to add a highlighted circle area with a text label on a specific coordinate. For example, 

Nous pourrions utiliser folium.Circle pour ajouter une zone circulaire mise en surbrillance avec une étiquette textuelle à une coordonnée spécifique. Par exemple,

In [7]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

and you should find a small yellow circle near the city of Houston and you can zoom-in to see a larger circle.

Now, let's add a circle for each launch site in data frame `launch_sites`

_TODO:_  Create and add `folium.Circle` and `folium.Marker` for each launch site on the site map

An example of folium.Circle:


Vous devriez trouver un petit cercle jaune près de la ville de Houston. Vous pouvez zoomer pour afficher un cercle plus grand.

Ajoutons maintenant un cercle pour chaque site de lancement dans le dataframe launch_sites.

À faire : Créer et ajouter les objets folium.Circle et folium.Marker pour chaque site de lancement sur la carte du site.

Exemple d'objet folium.Circle :

In [8]:
#`folium.Circle(coordinate, radius=1000, color='#000000', #fill=True).add_child(folium.Popup(...))`

#import folium
#from folium.features import DivIcon

# Initialisation de la carte (déjà créée dans votre notebook)
# site_map = folium.Map(location=nasa_coordinate, zoom_start=4)

# TODO: Create and add folium.Circle and folium.Marker for each launch site on the site map
for index, row in launch_sites_df.iterrows():
    # 1. Extraction des coordonnées (Latitude, Longitude) et du nom du site
    coordinate = [row['Lat'], row['Long']]
    site_name = row['Launch Site']
    
    # 2. Création et ajout du cercle entourant le site de lancement
    circle = folium.Circle(
        location=coordinate, 
        radius=1000, 
        color='#d35400', # Vous pouvez utiliser '#000000' ou la couleur orange native du projet
        fill=True
    ).add_child(folium.Popup(site_name))
    
    # 3. Création et ajout du marqueur textuel (DivIcon) pour afficher le nom du site
    marker = folium.Marker(
        location=coordinate,
        icon=DivIcon(
            icon_size=(20, 20),
            icon_anchor=(0, 0),
            html=f'<div style="font-size: 12px; color:#d35400;"><b>{site_name}</b></div>'
        )
    )
    
    # 4. Ajout des éléments sur la carte principale
    site_map.add_child(circle)
    site_map.add_child(marker)

# Affichage de la carte
site_map

An example of folium.Marker:

`folium.map.Marker(coordinate, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'label', ))`

In [9]:
# Initial the map
#site_map = folium.Map(location=nasa_coordinate, zoom_start=5)
# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label

In [10]:

# Coordinates for the center of the map (example: Kennedy Space Center)
nasa_coordinate = [28.5721, -80.6480]

# Initial the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)

# Example dataset: Launch site names and their coordinates
launch_sites = [
    {'name': 'KSC LC-39A', 'coord': [28.5721, -80.6480]},
    {'name': 'CCAFS SLC-40', 'coord': [28.5623, -80.5774]},
    {'name': 'VAFB SLC-4E', 'coord': [34.6321, -120.6106]}
]

# For each launch site, add a Circle and a Marker to the map
for site in launch_sites:
    coordinate = site['coord']
    site_name = site['name']
    
    # Add a Circle object based on its coordinate (Lat, Long)
    folium.Circle(
        location=coordinate,
        radius=1000, # Radius in meters
        color='#d35400',
        fill=True,
        fill_color='#d35400',
        fill_opacity=0.2
    ).add_to(site_map)
    
    # Add Launch site name as a custom Marker with DivIcon
    folium.Marker(
        location=coordinate,
        popup=site_name,
        icon=DivIcon(
            icon_size=(20, 20),
            icon_anchor=(0, 0),
            html='<div style="font-size: 12pt; color:#d35400;"><b>%s</b></div>' % site_name
        )
    ).add_to(site_map)

# Display the map
site_map

The generated map with marked launch sites should look similar to the following:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_markers.png">
</center>

Now, you can explore the map by zoom-in/out the marked areas
, and try to answer the following questions:
- Are all launch sites in proximity to the Equator line?
- Are all launch sites in very close proximity to the coast?

Also please try to explain your findings.


Vous pouvez maintenant explorer la carte en zoomant sur les zones indiquées et tenter de répondre aux questions suivantes :

Tous les sites de lancement sont-ils situés à proximité de l’équateur ?

Tous les sites de lancement sont-ils situés à proximité immédiate des côtes ?

Veuillez également expliquer vos observations.

## Réponses :

- Non tous les sites de lancement ne sont pas proches de l'équateur. VAFB est en Californie et ESAFS en Floride, tous deux dans l'hémisphère nord, loin de l'équteur.
- Oui, tous les sites de lancement sont situés à proximité immédiate des côtes. Ceci est souvent pour des raisons de sécurité, afin que les débris tombent dans l'océan.

# Task 2: Mark the success/failed launches for each site on the map

Next, let's try to enhance the map by adding the launch outcomes for each site, and see which sites have high success rates.
Recall that data frame spacex_df has detailed launch records, and the `class` column indicates if this launch was successful or not


Tâche 2 : Indiquer les lancements réussis/échoués pour chaque site sur la carte.

Ensuite, améliorons la carte en ajoutant les résultats des lancements pour chaque site et identifions les sites présentant des taux de réussite élevés. Rappelons que le tableau de données spacex_df contient des enregistrements de lancement détaillés, et que la colonne « class » indique si le lancement a réussi ou non.

In [11]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class
46    KSC LC-39A  28.573255 -80.646895      1
47    KSC LC-39A  28.573255 -80.646895      1
48    KSC LC-39A  28.573255 -80.646895      1
49  CCAFS SLC-40  28.563197 -80.576820      1
50  CCAFS SLC-40  28.563197 -80.576820      1
51  CCAFS SLC-40  28.563197 -80.576820      0
52  CCAFS SLC-40  28.563197 -80.576820      0
53  CCAFS SLC-40  28.563197 -80.576820      0
54  CCAFS SLC-40  28.563197 -80.576820      1
55  CCAFS SLC-40  28.563197 -80.576820      0

Next, let's create markers for all launch records. 
If a launch was successful `(class=1)`, then we use a green marker and if a launch was failed, we use a red marker `(class=0)`

Note that a launch only happens in one of the four launch sites, which means many launch records will have the exact same coordinate. Marker clusters can be a good way to simplify a map containing many markers having the same coordinate.


Ensuite, créons des marqueurs pour chaque lancement. Un lancement réussi (classe 1) sera représenté par un marqueur vert, et un lancement raté par un marqueur rouge (classe 0).

Notez qu'un lancement a lieu sur l'un des quatre sites de lancement, ce qui signifie que plusieurs lancements auront les mêmes coordonnées. Le regroupement des marqueurs permet de simplifier une carte comportant de nombreux marqueurs aux coordonnées identiques.

Let's first create a `MarkerCluster` object

In [12]:
marker_cluster = MarkerCluster()

_TODO:_ Create a new column in `launch_sites` dataframe called `marker_color` to store the marker colors based on the `class` value

In [13]:
# Fonction pour attribuer une couleur selon le résultat du lancement
def assign_marker_color(launch_outcome):
    if launch_outcome == 1:
        return 'green'
    else:
        return 'red'

# Application de la fonction pour créer la nouvelle colonne
spacex_df['marker_color'] = spacex_df['class'].apply(assign_marker_color)

In [ ]:

# Apply a function to check the value of `class` column
# If class=1, marker_color value will be green
# If class=0, marker_color value will be red

In [14]:
# Function to assign color to launch outcome
def assign_marker_color(launch_outcome):
    if launch_outcome == 1:
        return 'green'
    else:
        return 'red'
    
spacex_df['marker_color'] = spacex_df['class'].apply(assign_marker_color)
spacex_df.tail(10)

     Launch Site        Lat       Long  class marker_color
46    KSC LC-39A  28.573255 -80.646895      1        green
47    KSC LC-39A  28.573255 -80.646895      1        green
48    KSC LC-39A  28.573255 -80.646895      1        green
49  CCAFS SLC-40  28.563197 -80.576820      1        green
50  CCAFS SLC-40  28.563197 -80.576820      1        green
51  CCAFS SLC-40  28.563197 -80.576820      0          red
52  CCAFS SLC-40  28.563197 -80.576820      0          red
53  CCAFS SLC-40  28.563197 -80.576820      0          red
54  CCAFS SLC-40  28.563197 -80.576820      1        green
55  CCAFS SLC-40  28.563197 -80.576820      0          red

_TODO:_ For each launch result in `spacex_df` data frame, add a `folium.Marker` to `marker_cluster`

In [15]:

# On parcourt chaque ligne du DataFrame spacex_df
for index, record in spacex_df.iterrows():
    
    # 1. On crée l'objet Marker avec ses coordonnées (Latitude, Longitude)
    marker = folium.Marker(
        location=[record['Lat'], record['Long']],
        
        # 2. On personnalise la couleur de l'icône selon la réussite (vert) ou l'échec (rouge)
        icon=folium.Icon(color='white', icon_color=record['marker_color']),
        
        # Optionnel : Ajout d'une bulle info avec le nom du site de lancement
        popup=f"Site: {record['Launch Site']}"
    )
    
    # 3. On ajoute le marqueur directement au groupe marker_cluster
    marker_cluster.add_child(marker)

# 4. (Rappel) N'oubliez pas d'ajouter le cluster à votre carte principale si ce n'est pas déjà fait
# site_map.add_child(marker_cluster)

In [16]:
# Add marker_cluster to current site_map
site_map.add_child(marker_cluster)

# for each row in spacex_df data frame
# create a Marker object with its coordinate
# and customize the Marker's icon property to indicate if this launch was successed or failed, 
# e.g., icon=folium.Icon(color='white', icon_color=row['marker_color']
for index, record in spacex_df.iterrows():
    # TODO: Create and add a Marker cluster to the site map
    # marker = folium.Marker(...)
    marker_cluster.add_child(marker)

site_map

Your updated map may look like the following screenshots:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster.png">
</center>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster_zoomed.png">
</center>


From the color-labeled markers in marker clusters, you should be able to easily identify which launch sites have relatively high success rates.

Grâce aux marqueurs de couleur regroupés en grappes, vous devriez pouvoir identifier facilement les sites de lancement présentant des taux de réussite relativement élevés.

## Commentaire :
Les sites de lancement marqués par des couleurs indiquant un taux de succès élevé sont facilement identifiables grâce à la prédominance de ces couleurs dans leurs grappes  respectives. Donc les sites de lancement relativement élevés sont CCAFS SLC-40 disposant de 33 lancements et KSC LC-39 qui a 13 lancements.

# TASK 3: Calculate the distances between a launch site to its proximities

Next, we need to explore and analyze the proximities of launch sites.

Let's first add a `MousePosition` on the map to get coordinate for a mouse over a point on the map. As such, while you are exploring the map, you can easily find the coordinates of any points of interests (such as railway)

In [22]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

## Réponse :
Les sites de lancement KSC (LC-39A) et CAFS (SLC-40) sont situés à proximités de l'autoroute US 1, de la SR 321 et du littoral. La SR 3 est également dans les environs.

You can calculate the distance between two points on the map based on their `Lat` and `Long` values using the following method:

Vous pouvez calculer la distance entre deux points sur la carte en fonction de leurs valeurs de latitude et de longitude en utilisant la méthode suivante :

In [23]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

_TODO:_ Mark down a point on the closest coastline using MousePosition and calculate the distance between the coastline point and the launch site.

In [24]:
# find coordinate of the closet coastline
# e.g.,: Lat: 28.56367  Lon: -80.57163
# distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)

In [25]:
# 1. Définir les coordonnées (Exemple avec Cap Canaveral)
launch_site_lat = 28.56319
launch_site_lon = -80.57682
coastline_lat = 28.56367
coastline_lon = -80.57163

# 2. Calculer la distance en utilisant la fonction existante
distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)

# 3. Créer et ajouter un marqueur (Marker) sur le point de la côte
distance_marker = folium.Marker(
    [coastline_lat, coastline_lon],
    icon=DivIcon(
        icon_size=(20, 20),
        icon_anchor=(0, 0),
        html=f'<div style="font-size: 12pt; color:#d35400;"><b>{distance_coastline:.2f} KM</b></div>',
    )
)
site_map.add_child(distance_marker)

# 4. Tracer une ligne (PolyLine) entre le site de lancement et la côte
lines = folium.PolyLine(
    locations=[[launch_site_lat, launch_site_lon], [coastline_lat, coastline_lon]], 
    weight=1
)
site_map.add_child(lines)


_TODO:_ After obtained its coordinate, create a `folium.Marker` to show the distance

In [28]:
import math
#import folium
from folium.plugins import MousePosition

# --- Fonction pour calculer la distance (Formule de Haversine) ---
def calculate_distance(lat1, lon1, lat2, lon2):
    # Rayon de la Terre en kilomètres
    R = 6373.0

    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)

    dlon = lon2_rad - lon1_rad
    dlat = lat2_rad - lat1_rad

    a = math.sin(dlat / 2)**2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    distance = R * c
    return distance

# --- Configuration initiale de la carte ---
# Coordonnées du site de lancement (Exemple : Cape Canaveral)
launch_site_lat = 28.56319
launch_site_lon = -80.57683

site_map = folium.Map(location=[launch_site_lat, launch_site_lon], zoom_start=12)

# Ajouter l'outil MousePosition pour trouver facilement les coordonnées au survol
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)
site_map.add_child(mouse_position)

# --- Point de lancement : Marqueur ---
folium.Marker(
    [launch_site_lat, launch_site_lon],
    popup='Site de lancement',
    icon=folium.Icon(color='blue', icon='rocket')
).add_to(site_map)

# ==========================================
# 1. TODO: Définir la coordonnée de la côte trouvée et calculer la distance
# ==========================================
# Coordonnées de la côte la plus proche trouvée via MousePosition (Exemple)
coastline_lat = 28.56367
coastline_lon = -80.57163

# Calcul de la distance
distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)


# ==========================================
# 2. TODO: Créer un folium.Marker pour afficher la distance
# ==========================================
# Créer le marqueur avec une icône personnalisée (DivIcon) pour afficher du texte HTML
distance_marker = folium.Marker(
    [coastline_lat, coastline_lon],
    icon=folium.DivIcon(
        icon_size=(20, 20),
        icon_anchor=(0, 0),
        html='<div style="font-size: 12pt; color: #d35400; font-weight: bold;"><b>{:10.2f} km</b></div>'.format(distance_coastline),
    )
)
site_map.add_child(distance_marker)


# ==========================================
# 3. BONUS: Tracer une ligne entre le site de lancement et la côte
# ==========================================
coordinates = [[launch_site_lat, launch_site_lon], [coastline_lat, coastline_lon]]
lines = folium.PolyLine(locations=coordinates, weight=2, color='red')
site_map.add_child(lines)

# Afficher la carte (dans un notebook Jupyter)
# site_map

In [ ]:
# Create and add a folium.Marker on your selected closest coastline point on the map
# Display the distance between coastline point and launch site using the icon property 
# for example
# distance_marker = folium.Marker(
#    coordinate,
#    icon=DivIcon(
#        icon_size=(20,20),
#        icon_anchor=(0,0),
#        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance),
#        )
#    )

_TODO:_ Draw a `PolyLine` between a launch site to the selected coastline point

In [32]:
#import folium
from math import sin, cos, sqrt, atan2, radians

# Fonction de calcul de distance (formule de Haversine)
def calculate_distance(lat1, lon1, lat2, lon2):
    # Rayon de la Terre en kilomètres
    R = 6373.0

    lat1_rad = radians(lat1)
    lon1_rad = radians(lon1)
    lat2_rad = radians(lat2)
    lon2_rad = radians(lon2)

    dlon = lon2_rad - lon1_rad
    dlat = lat2_rad - lat1_rad

    a = sin(dlat / 2)**2 + cos(lat1_rad) * cos(lat2_rad) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

# --- Configuration initiale ---
# Exemple de coordonnées (Launch site : Cape Canaveral LC-39A)
launch_site_lat = 28.57325
launch_site_lon = -80.64689

# 1. TODO: Coordonnées de la côte la plus proche identifiées avec MousePosition
coastline_lat = 28.56367
coastline_lon = -80.57163

# Calcul de la distance
distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)

# Création de la carte Folium centrée sur le site de lancement
site_map = folium.Map(location=[launch_site_lat, launch_site_lon], zoom_start=12)


# 2. TODO: Créer un folium.Marker personnalisé pour afficher la distance
distance_marker = folium.Marker(
    [coastline_lat, coastline_lon],
    icon=folium.DivIcon(
        icon_size=(20, 20),
        icon_anchor=(0, 0),
        html=f'<div style="font-size: 12pt; color:#d35400;"><b>{distance_coastline:.2f} KM</b></div>',
    )
)
site_map.add_child(distance_marker)


# 3. TODO: Dessiner une PolyLine entre le site de lancement et le point côtier
coordinates = [[launch_site_lat, launch_site_lon], [coastline_lat, coastline_lon]]
lines = folium.PolyLine(
    locations=coordinates,
    weight=1,
    color='blue'
)
#site_map.add_child(lines)

# Afficher la carte (dans un notebook Jupyter)
# site_map

In [33]:
# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
# lines=folium.PolyLine(locations=coordinates, weight=1)
site_map.add_child(lines)

Your updated map with distance line should look like the following screenshot:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_distance.png">
</center>


_TODO:_ Similarly, you can draw a line betwee a launch site to its closest city, railway, highway, etc. You need to use `MousePosition` to find the their coordinates on the map first

In [34]:

import folium
from folium.plugins import MousePosition
import math

# 1. Fonction pour calculer la distance (Formule de Haversine)
def calculate_distance(lat1, lon1, lat2, lon2):
    # Rayon de la Terre en kilomètres
    R = 6373.0
    
    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)
    
    dlon = lon2_rad - lon1_rad
    dlat = lat2_rad - lat1_rad
    
    a = math.sin(dlat / 2)**2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    
    return R * c

# Initialisation de la carte et du MousePosition pour trouver les coordonnées
launch_site_lat, launch_site_lon = 28.56319, -80.57682 # Exemple : CCAFS SLC-40
site_map = folium.Map(location=[launch_site_lat, launch_site_lon], zoom_start=10)

formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)
site_map.add_child(mouse_position)


# =====================================================================
# TODO 1 & 2 : Trouver la côte, calculer la distance et ajouter le Marker
# =====================================================================

# Coordonnées trouvées grâce à MousePosition sur le littoral le plus proche
coastline_lat, coastline_lon = 28.56367, -80.57163 

# Calcul de la distance
distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)

# Création du marqueur avec une icône personnalisée affichant la distance
distance_marker = folium.Marker(
    [coastline_lat, coastline_lon],
    icon=folium.DivIcon(
        icon_size=(20, 20),
        icon_anchor=(0, 0),
        html=f'<div style="font-size: 12pt; color:#d35400;"><b>{distance_coastline:.2f} KM</b></div>',
    )
)
site_map.add_child(distance_marker)

# Tracer la ligne (PolyLine) entre le site et la côte
lines = folium.PolyLine(
    locations=[[launch_site_lat, launch_site_lon], [coastline_lat, coastline_lon]], 
    weight=1
)
site_map.add_child(lines)


# =====================================================================
# TODO 4 : Répéter l'opération pour une ville, une autoroute ou voie ferrée
# =====================================================================

# Exemple avec la ville la plus proche (Titusville)
city_lat, city_lon = 28.61200, -80.80700
distance_city = calculate_distance(launch_site_lat, launch_site_lon, city_lat, city_lon)

# Marqueur pour la ville
city_marker = folium.Marker(
    [city_lat, city_lon],
    icon=folium.DivIcon(
        icon_size=(20, 20),
        icon_anchor=(0, 0),
        html=f'<div style="font-size: 12pt; color:#2980b9;"><b>{distance_city:.2f} KM</b></div>',
    )
)
site_map.add_child(city_marker)

# Ligne vers la ville
lines_city = folium.PolyLine(
    locations=[[launch_site_lat, launch_site_lon], [city_lat, city_lon]], 
    weight=1,
    color='blue'
)
site_map.add_child(lines_city)

# Afficher la carte (si vous êtes sur un notebook Jupyter)
# site_map

A railway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/railway.png">
</center>

A highway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/highway.png">
</center>

A city map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/city.png">
</center>

In [35]:
# Create a marker with distance to a closest city, railway, highway, etc.
# Draw a line between the marker to the launch site

In [36]:
#import folium
from math import sin, cos, sqrt, atan2, radians

# ----------------------------------------------------
# 1. FONCTION DE CALCUL DE DISTANCE (Formule de Haversine)
# ----------------------------------------------------
def calculate_distance(lat1, lon1, lat2, lon2):
    # Rayon de la Terre en kilomètres
    R = 6373.0

    lat1_rad = radians(lat1)
    lon1_rad = radians(lon1)
    lat2_rad = radians(lat2)
    lon2_rad = radians(lon2)

    dlon = lon2_rad - lon1_rad
    dlat = lat2_rad - lat1_rad

    a = sin(dlat / 2)**2 + cos(lat1_rad) * cos(lat2_rad) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    return R * c

# ----------------------------------------------------
# 2. CONFIGURATION INITIALE DE LA CARTE & DU SITE
# ----------------------------------------------------
# Exemple avec le site de lancement Cape Canaveral (LC-39A)
launch_site_lat = 28.57325
launch_site_lon = -80.64689

# Création de la carte de base
site_map = folium.Map(location=[launch_site_lat, launch_site_lon], zoom_start=12)

# Ajout du plugin MousePosition pour trouver les coordonnées au survol
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = folium.plugins.MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)
site_map.add_child(mouse_position)

# ----------------------------------------------------
# 3. COORDONNÉES DES POINTS LES PLUS PROCHES (À trouver via MousePosition)
# ----------------------------------------------------
# Remplacez ces coordonnées fictives par celles trouvées avec votre souris :
coordinates_poi = {
    "coastline": {"lat": 28.56367, "lon": -80.57163, "color": "blue"},
    "city":      {"lat": 28.61200, "lon": -80.80700, "color": "green"},
    "railway":   {"lat": 28.57245, "lon": -80.58528, "color": "orange"},
    "highway":   {"lat": 28.57304, "lon": -80.65545, "color": "red"}
}

# ----------------------------------------------------
# 4. CRÉATION DES MARQUEURS ET DES LIGNES (POLY_LINES)
# ----------------------------------------------------
for poi_name, coords in coordinates_poi.items():
    # Calcul de la distance entre le site et le POI
    distance = calculate_distance(launch_site_lat, launch_site_lon, coords["lat"], coords["lon"])
    
    # TODO 2 & 5: Créer un folium.Marker pour afficher la distance
    distance_marker = folium.Marker(
        [coords["lat"], coords["lon"]],
        icon=folium.DivIcon(
            icon_size=(20, 20),
            icon_anchor=(0, 0),
            html=f'<div style="font-size: 12pt; color:{coords["color"]};"><b>{distance:.2f} KM</b></div>',
        )
    )
    site_map.add_child(distance_marker)
    
    # TODO 4: Tracer une ligne (PolyLine) entre le site de lancement et le POI
    line_coordinates = [[launch_site_lat, launch_site_lon], [coords["lat"], coords["lon"]]]
    lines = folium.PolyLine(
        locations=line_coordinates, 
        weight=2, 
        color=coords["color"]
    )
    site_map.add_child(lines)

# Affichage ou sauvegarde de la carte
# site_map.save("launch_site_distances.html")
site_map


After you plot distance lines to the proximities, you can answer the following questions easily:
- Are launch sites in close proximity to railways?
- Are launch sites in close proximity to highways?
- Are launch sites in close proximity to coastline?
- Do launch sites keep certain distance away from cities?

Also please try to explain your findings.

Après avoir tracé les lignes de distance vers les proximités, vous pouvez facilement répondre aux questions suivantes :

Les sites de lancement sont-ils à proximité des voies ferrées ?
Les sites de lancement sont-ils à proximité des autoroutes ?
Les sites de lancement sont-ils à proximité du littoral ?
Les sites de lancement maintiennent-ils une certaine distance des villes ?
Veuillez également essayer d'expliquer vos conclusions.

## Réponses :
Les sites de lancement sont en proximité des voies ferrées, des autoroutes et du littoral. Ils semblent maintenir une certaine distance des villes.

# Next Steps:

Now you have discovered many interesting insights related to the launch sites' location using folium, in a very interactive way. Next, you will need to build a dashboard using Ploty Dash on detailed launch records.

Étapes suivantes :

Vous avez maintenant découvert de nombreuses informations intéressantes sur l’emplacement des sites de lancement grâce à Folium, et ce de manière très interactive. L’étape suivante consiste à créer un tableau de bord avec Ploty Dash à partir des données détaillées des lancements.

## Authors

[Yan Luo](https://www.linkedin.com/in/yan-luo-96288783/)

### Other Contributors

Joseph Santarcangelo

## Change Log

|Date (YYYY-MM-DD)|Version|Changed By|Change Description|
|-|-|-|-|
|2021-05-26|1.0|Yan|Created the initial version|

Copyright © 2021 IBM Corporation. All rights reserved.